### ISSUE TITLE
How do I import padstone.sql on prefixed database tables?

### ISSUE THREAD

**Issue by mattsah** [imarc/padstone#20]
I don't see a solution for this.

**Comment by khamer** [comment]
Because the SQL file is just a database export, I don't think this is a feature that we can add right now. It might be possible through piping through awk if you wanted to add a prefix on the fly. The plugin ([nerds-and-company/schematic](https://github.com/nerds-and-company/schematic)) we used to use to avoid the SQL file doesn't support 3.1+.

**Comment by khamer** [comment]
Closing as can't fix - sorry.
